### ISSUE TITLE
TabBar doesn't support RTL

### ISSUE THREAD

**Issue by Assem-Hafez** [react-native-community/react-native-tab-view#200]
In RTL views the TabBar tabs are reversed so their order and selection doesn't match the swipe gesture and the underline animation.

it would be great if the order of tabs in RTL views matches that of LTR views.

**Comment by dastoori** [comment]
I've fixed this functionality in #194, it will be available in the next version.
You can also see this: https://github.com/react-native-community/react-native-tab-view/issues/184#issuecomment-292746177

**Comment by satya164** [comment]
Re-opening this since `TabBar` with `scrollEnabled` still doesn't support RTL.

**Comment by satya164** [comment]
Closing in favour of #184. Let's track all RTL related issues there.

**Comment by ozanhonamlioglu** [comment]
[Hey guys, you can check my RTL support changes.](https://github.com/ozanhonamlioglu/react-native-tab-view/commit/6beb5c93791b1fb24b725b90d55a01d5976f61bc#diff-bb8bbc7571b2d43dea35735cd1cce27f1e73c2cb219349b5517d6bcbf4a0f9ed)

I just changed 3 files and now everything works as expected.
