### ISSUE TITLE
Keep footer fixed at the bottom of the screen when keyboard opens

### ISSUE THREAD

**Issue by Jarrio** [react-native-community/react-native-tab-view#273]
Is there any way this can be accomplished? I tried setting `position: absolute;` but it seems like the tabs keep wanting to move upwards with keyboard
![gif](https://cloud.githubusercontent.com/assets/748557/26659283/61341802-4667-11e7-9a4b-3e607c6b6ca8.gif)

**Comment by junshengpierre** [comment]
You could set `android:windowSoftInputMode="adjustPan"` in your main activity in `android/app/src/AndroidManifest.xml`. However, this removes the android soft keyboard's behaviour of pushing the view up to make space for the keyboard in the entire app. 

Does anyone have a way to prevent only the tab bar from being pushed up?

**Comment by illl48** [comment]
@Jarrio hi, did you find out any solution? thanks!

**Comment by cleandersonlobo** [comment]
> android/app/src/AndroidManifest.xml

```
<activity
.....
android:windowSoftInputMode="stateAlwaysHidden|adjustPan" 
.....
```
worked for me.

**Comment by Danny-weebo** [comment]
+1

**Comment by seniorshahmar** [comment]
You can make fixed height and minHeight for boxes and it will prevent minimizing height of boxes.
Example below:
<View style={{position: 'absolute',bottom: 0, top: 0, width: '100%', height: screen.height, minHeight: screen.height}}>
Content goes here
</View>

**Comment by ankitkante** [comment]
@junshengpierre @cleandersonlobo Your solutions will work for ejected apps only. Is there any solution for non-ejected CRNA apps?

**Comment by ggepenyan** [comment]
Any solution for crna?

**Comment by Royalone-mobile** [comment]
> > android/app/src/AndroidManifest.xml
> 
> ```
> <activity
> .....
> android:windowSoftInputMode="stateAlwaysHidden|adjustPan" 
> .....
> ```
> worked for me.

Thank you very much

**Comment by meetjpatel** [comment]
> You can make fixed height and minHeight for boxes and it will prevent minimizing height of boxes.
> Example below:
> <View style={{position: 'absolute',bottom: 0, top: 0, width: '100%', height: screen.height, minHeight: screen.height}}>
> Content goes here
After struggling for 3 days, I came across this and it worked! Thanks!

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by imrahulpatel** [comment]
This issue is still in android in IOS it's work perfect 
![image](https://user-images.githubusercontent.com/9443277/58966669-54f80b00-87d0-11e9-98aa-1c30d4d96b3d.png)

**Comment by Alix-stack** [comment]
> stateAlwaysHidden|adjustPan

thanks it's working for me too

**Comment by HessiPard** [comment]
Hi, I have a similira Problem with `adjustPan` property.
if you have TextInput in all tabs at bottom of the page, soft keyboard only pushes up screen to see input in first tab not other tabs. more info at this [thread](https://github.com/satya164/react-native-tab-view/issues/1129)

**Comment by musthafa-pa** [comment]
@cleandersonlobo Thanks, man. It worked for me.

**Comment by Vishoodi** [comment]
Hi I also have same problem. Although I try stateAlwaysHidden|adjustPan it's not work for me
