### ISSUE TITLE
Tab title not update when use I18n to change language

### ISSUE THREAD

**Issue by vietnd87** [react-native-community/react-native-tab-view#642]
Hi,

As entry, I use I18n to setup multiple languages for my app. All other text inside tab content be updated after change I18n locale but only titles on Tab-bar not update. Can you help me to solved it?

Thanks!

**Comment by satya164** [comment]
Hey, I just released a new alpha `2.0.0-alpha.0` of the library. It's rewritten using [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) addresses a many platform specific bugs and performance problems. The documentation is updated as well.

Please try the new version and see if it addresses your issue. If not, please open a new issue following the issue template.

**Comment by lumberman** [comment]
Problem still exists in "react-native-tab-view": "^2.15.2".
Tab strings won't refresh on language change.
