### ISSUE TITLE
unable to resolve ./pagerDefault  module from react-native-tab-view

### ISSUE THREAD

**Issue by BharathBunty** [react-native-community/react-native-tab-view#727]
./pager default is not found can you please help me to fix this issue

**Comment by epurban** [comment]
Also getting the same error when upgrading from 1.3.2 to 2.0.3

**Comment by BharathBunty** [comment]
after you install  ->react-native-tab-view 
and try this  react-native link react-native-tab-view  
it may be solve your issue

**Comment by arnotixe** [comment]
I had the same issue after upgrading and running straight after; clearing metro cache (linux: rm -fr /tmp/metro-*) and running again solved this. Passed ages barking up different wrong trees first.

**Comment by levani** [comment]
I'm using react-native-tab-view with expo and can't fix this problem... Clearing cache does not work. Any ideas?

**Comment by BharathBunty** [comment]
uninstall react-native-tab-view and   try react-native --reset cache .  and install again ,link it & see it may work out ..

**Comment by jb9229** [comment]
i solved with expo, after 'yarn cache clean'

**Comment by ITsolution-git** [comment]
I tried to clean my npm cache, but I still get `unable tor resolve ./pageDefault module`.
I am running on CRNA. Did someone solve this one successfully?

**Comment by jb9229** [comment]
This is my solution in Expo:
 1. yarn remove react-native-tab-view
 2. yarn cache clean
 3. yarn add react-native-tab-view

**Comment by thomashagstrom** [comment]
Like @ITsolution-git I get this issue out of the box, with Expo 32.
Followed the above steps by @jb9229 without luck.

```bash
Trying to open the project in iOS simulator...
Opening exp://127.0.0.1:19000 in iOS simulator

Press ? to show a list of all available commands.
Unable to resolve "./PagerDefault" from "node_modules/react-native-tab-view/src/index.js"
Unable to resolve "./PagerDefault" from "node_modules/react-native-tab-view/src/index.js"
Building JavaScript bundle [=========================================] 99%
```

**package.json**

```json
 "dependencies": {
    "@babel/runtime": "7.0.0",
    "@expo/samples": "2.1.1",
    "@monterosa/react-native-parallax-scroll": "^1.8.0",
    "axios": "^0.18.0",
    "expo": "^32.0.6",
    "lodash": "^4.17.11",
    "moment-timezone": "^0.5.23",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-actionsheet": "^2.4.2",
    "react-native-cross-components": "^0.2.7",
    "react-native-dotenv": "^0.2.0",
    "react-native-dropdown-autocomplete": "^1.0.10",
    "react-native-event-listeners": "^1.0.3",
    "react-native-paper": "^2.15.2",
    "react-native-simple-stepper": "^2.1.3",
    "react-native-tab-view": "^2.2.0",
    "react-navigation": "^3.0.9",
    "react-navigation-material-bottom-tabs": "^1.0.0",
    "sentry-expo": "^1.11.2",
    "shortid": "^2.2.14",
    "xregexp": "^4.2.4"
  },```

**Comment by kgra** [comment]
The same problem still occurs.

 Unable to resolve module `./PagerDefault` from `...\node_modules\react-native-tab-view\src\index.j`

Uninstalling and installing react-native-tab-view does not help. I am working outside of expo. Please help

**Comment by satya164** [comment]
Try running `yarn start --reset-cache` or `react-native start --reset-cache`
